#!/bin/bash
if [ $(whoami) != "root" ]
then
  echo "Need to be root.  Exiting."
  exit 1
fi
systemctl disable display-manager
/sbin/fdisk /dev/mmcblk1 <<EOF
d
4
n
4


N
w
EOF
/sbin/resize2fs /dev/mmcblk1p4
rm /etc/apt/sources.list
echo "deb https://deb.debian.org/debian/ sid main contrib non-free" >>/etc/apt/sources.list
#sed -i -e "s/20221225T084846Z/20230724T141507Z/" /etc/apt/sources.list
apt update
apt install -y debian-ports-archive-keyring
apt update
apt install -y usrmerge
apt-get install -y gh
git config --global user.email "frank@halasz.org"
git config --global user.name "Frank Halasz"
mkdir /zynthian
cd /zynthian
git clone -b zynia https://github.com/zynia-org/zynthian-sys
apt install -y cmake
mkdir /log
cat > /zynthian/zynthian-sys/scripts/do_vf2 <<EOF
#!/bin/bash
cd /zynthian/zynthian-sys/scripts
./setup_system_vf2.sh 2>&1 | tee /log/setup.log
EOF
chmod +x /zynthian/zynthian-sys/scripts/do_vf2
