#!/bin/bash
if [ $(whoami) != "root" ]
then
  echo "Need to be root.  Exiting."
  exit 1
fi
systemctl disable display-manager
/sbin/fdisk /dev/nvme0n1 <<EOF
d
4
n
4


N
w
EOF
/sbin/resize2fs /dev/nvme0n1p4
rm /etc/apt/sources.list
echo "deb https://deb.debian.org/debian/ sid main contrib non-free" >>/etc/apt/sources.list
apt update
#apt install -y debian-ports-archive-keyring
#echo "deb https://snapshot.debian.org/archive/debian-ports/20230724T141507Z unstable main" >>/etc/apt/sources.list
#apt update

apt install -y usrmerge
apt-get install -y gh
apt install -y cmake
git config --global user.email "frank@halasz.org"
git config --global user.name "Frank Halasz"
#
mkdir /zynthian
cd /zynthian
git clone -b oram-zynia https://github.com/zynia-org/zynthian-sys zynia
mkdir /log
#
cat > /zynthian/zynia/do_vf2 <<EOF
#!/bin/bash
cd /zynthian/zynia/scripts
./setup_system_vf2_bookworm.sh 2>&1 | tee /log/setup.log
#
cd /vf2
tar xzf IMG_GPU-xorg.tar.gz
cp -rp IMG_GPU-xorg/lib/* /lib
cp -rp IMG_GPU-xorg/etc/* /etc
cp -rp IMG_GPU-xorg/usr/* /usr
rm -rf IMG_GPU-xorg
#
cd /zynthian
#
EOF
chmod +x /zynthian/zynia/do_vf2
