#!/bin/bash
if [ $(whoami) != "root"]
then
  echo "Need to be root.  Exiting."
  exit 1
fi
systemctl disable display-manager
/sbin/fdisk /dev/mmcblk1 <<EOF
d
4
n
4


N
w
EOF
/sbin/resize2fs /dev/mmcblk1p4
echo "deb https://deb.debian.org/debian/ sid main contrib non-free" >>/etc/apt/sources.list
sed -i -e "s/20221225T084846Z/20230724T141507Z/" /etc/apt/sources.list
apt update
apt install -y debian-ports-archive-keyring
apt update
apt install -y usrmerge
apt-get install -y gh
git config --global user.email "frank@halasz.org"
git config --global user.name "Frank Halasz"
mkdir /zynthian
cd /zynthian
git clone https://github.com/zynia-org/zynthian-sys
cd zynthian-sys
git fetch origin zynia
git checkout zynia
apt install -y cmake

